syntax = "proto3";

package user;

option go_package = "crud-microservice/pb;pb";

service UserService {
    rpc CreateUser(CreateUserRequest) returns (UserResponse);
    rpc GetUser(GetUserRequest) returns (UserResponse);
    rpc GetAllUsers(GetAllUsersRequest) returns (UserListResponse);
    rpc UpdateUser(UpdateUserRequest) returns (UserResponse);
    rpc DeleteUser(DeleteUserRequest) returns (DeleteUserResponse);
}

message CreateUserRequest {
    string name = 2;
    string email = 3;
}

message GetUserRequest {
    string id = 1;
}

message GetAllUsersRequest {}

message UpdateUserRequest {
    string id = 1;
    string name = 2;
    string email = 3;
}

message DeleteUserRequest {
    string id = 1;
}

message DeleteUserResponse {
    string message = 1;
}

message UserResponse {
    string id = 1;
    string name = 2;
    string email = 3;
}

message UserListResponse {
    repeated UserResponse users = 1;
}

