version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"

  user-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_CONN: postgres://user:password@db:5432/userdb?sslmode=disable
    depends_on:
      - db